Repository yookeunbyul/Algorithm-Study, pull requests merged in 2024-09, with the labels that each got.

#23 2week-sylvia
  sylvia/2주차/[문제 12] 주식 가격.md
  sylvia/2주차/[문제 16] 기능 개발.md
  sylvia/2주차/[문제 18] 두 개의 수로 특정 값 만들기.md
  sylvia/2주차/[문제 19] 문자열 해싱을 이용한 검색 함수 만들기.md
  sylvia/2주차/[문제 20] 완주하지 못한 선수.md
Labels: documentation, 🚀 주간 제출

#22 2week-commeci
  commeci/2주차/[문제 11] 짝지어 제거하기.md
  commeci/2주차/[문제 12] 주식 가격.md
  commeci/2주차/[문제 13] 크레인 인형 뽑기 게임.md
  commeci/2주차/[문제 14] 표 편집.md
  commeci/2주차/[문제 15] 요세푸스 문제.md
  commeci/2주차/[문제 16] 기능 개발.md
  commeci/2주차/[문제 17] 카드 뭉치.md
  commeci/2주차/[문제 18] 두 개의 수로 특정 값 만들기.md
  commeci/2주차/[문제 19] 문자열 해싱을 이용한 검색 함수 만들기.md
  commeci/2주차/[문제 20] 완주하지 못한 선수.md
Labels: 🚀 주간 제출

#21 2week-jongwon
  jongwon/2주차/문제 12 주식 가격.md
  jongwon/2주차/문제 16 기능개발.md
  jongwon/2주차/문제 18 두 개의 수로 특정 값 만들기.md
  jongwon/2주차/문제 19 문자열 해싱을 이용한 검색 함수 만들기.md
  jongwon/2주차/문제 20 완주하지 못한 선수.md
Labels: 🚀 주간 제출

#19 2week-ayoung
  ayoung/2주차/[문제 12] 주식 가격.md
  ayoung/2주차/[문제 16] 기능 개발.md
  ayoung/2주차/[문제 19] 문자열 해싱을 이용한 검색 함수 만들기.md
  ayoung/2주차/[문제 20] 완주하지 못한 선수.md
Labels: 🚀 주간 제출

#26 3week-commeci
  commeci/3주차/[문제 26] 트리 순회.md
  commeci/3주차/[문제 27] 이진 탐색 트리 구현.md
  commeci/3주차/[문제 28] 예상 대진표.md
  commeci/3주차/[문제 29] 다단계 칫솔 판매.md
  commeci/3주차/[문제 30] 미로탈출.md
Labels: 🚀 주간 제출

#25 3week-ayoung
  ayoung/3주차/[문제 27] 이진 탐색 트리 구현.md
  ayoung/3주차/[문제 28] 예상 대진표.md
  ayoung/3주차/[문제 29] 다단계 칫솔 판매.md
  ayoung/3주차/[문제 30] 미로 탈출.md
Labels: 🚀 주간 제출

#27 3week-sylvia
  sylvia/3주차/[문제 27] 이진 탐색 트리 구현.md
  sylvia/3주차/[문제 28] 예상 대진표.md
  sylvia/3주차/[문제 29] 다단계 칫솔 판매.md
Labels: 🚀 주간 제출

#24 3week-jongwon
  jongwon/3주차/문제 27 이진 탐색 트리 구현.md
  jongwon/3주차/문제 28 예상 대진표.md
  jongwon/3주차/문제 29 다단계 칫솔 판매.md
  jongwon/3주차/문제 30 미로 탈출.md
Labels: 🚀 주간 제출

#28 [문제 27] 이진 탐색 트리 구현-sylvia
  sylvia/3주차/[문제 27] 이진 탐색 트리 구현.md
Labels: 🔧 수정사항 적용

#32 4week-sylvia
  sylvia/4주차/[문제 34] 폰켓몬.md
  sylvia/4주차/[문제 35] 영어 끝말잇기.md
  sylvia/4주차/[문제 36] 전화번호 목록.md
Labels: 🚀 주간 제출

#31 4week-commeci
  commeci/4주차/[문제 34] 포켓몬.md
  commeci/4주차/[문제 35] 영어 끝말잇기.md
  commeci/4주차/[문제 36] 전화번호 목록.md
  commeci/4주차/[문제 37] 섬 연결하기.md
Labels: 🚀 주간 제출
